### PR TITLE
Added important achievement events

### PR DESCRIPTION
**Pull request by ThatTechedGuy**
- Added a function which can be used to track 'spaceship boss avoided' events
- Added an event which triggers when an unlocked achievement is being displayed on the screen. This can be used to spawn bonus items or change the attire of the main character. 
- Minor event constant refactors 
- Better javadoc for AchievementsHelper

### CODE REVIEW

**Comment by ThatTechedGuy** [comment]
@lisslulay can you checkout to this branch and track the avoid event for spaceship boss. 
`AchievementsHelper.getInstance().trackSpaceshipAvoidSuccess()` has to be invoked as discussed.

**Comment by ThatTechedGuy** [comment]
@Yonarp @kprohith As discussed, tracked the event where unlocked achievements are being displayed mid game, so that you can listen to it to spawn attires and bonus items. 
`AchievementsHelper.getInstance().getEvents().addListener(AchievementsHelper.EVENT_UNLOCKED_ACHIEVEMENT_DISPLAYED, (achievement) -> { perform Tasks} );`

**Comment by lisslulay** [comment]
> @lisslulay can you checkout to this branch and track the avoid event for spaceship boss?
> `AchievementsHelper.getInstance().trackSpaceshipAvoidSuccess()` has to be invoked as discussed in #264

Okay, I'll do that ASAP.

**Review by lisslulay — COMMENTED** [review]
Completed "EVENT_SPACESHIP_AVOIDED" trigger

**Review by Butcanudothis — APPROVED** [review]
Looks good ⚡

**Review by Yonarp — APPROVED** [review]

**Pull request merged**
